name: CI
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.15.6"
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Build
        run: go build .
      - name: Lint & Vet
        run: |
          go vet .
          golint .
      - name: Test
        run: |
          go test -v ./...

